---
- name: Deploy backend-node instance
  hosts: webservers
  become: yes

  vars:
    instance_name: "{{ instance_name }}"
    remote_base_dir: "{{ remote_base_dir | default('/opt/instances') }}"
    instance_dir: "{{ remote_base_dir }}/{{ instance_name }}"

  tasks:

    - name: Crear directorio de instancia
      file:
        path: "{{ instance_dir }}"
        state: directory
        mode: '0755'

    - name: Calcular puertos dinámicos
      set_fact:
        backend_port: "{{ 4000 + (instance_name | hash('md5') | int(base=16) % 1000) }}"
        mysql_port: "{{ 6000 + (instance_name | hash('md5') | int(base=16) % 1000) }}"

    - name: Render docker-compose
      template:
        src: docker-compose.yml.j2
        dest: "{{ instance_dir }}/docker-compose.yml"

    - name: Render .env
      template:
        src: .env.j2
        dest: "{{ instance_dir }}/.env"

    - name: Crear carpeta mysql_data
      file:
        path: "{{ instance_dir }}/mysql_data"
        state: directory

    - name: Levantar contenedores
      shell: |
        cd {{ instance_dir }}
        docker compose up -d --remove-orphans
      args:
        executable: /bin/bash